### ISSUE TITLE
CIFAR10 not work on epig

### ISSUE THREAD

**Issue by odroidodroid** [fbickfordsmith/epig#3]
I added cifar10 to your code and tried active learning. In results, random is better than epig when i used convolutional_nn and resnet18 as a model. 

Is there any reason that epig is not working on cifar10?

thanks

Youngjin kim.

**Comment by fbickfordsmith** [comment]
Hi Youngjin!

Just following up on this and our email exchange from when this first came up.

It's pretty hard to get Bayesian active learning to work well on CIFAR-10 with standard fully supervised models. In our AISTATS 2024 paper we suggest switching to semi-supervised models as a solution.

Let me know if you have any issues using the updated code.

Freddie
